import { Property, Lead, Comp } from "./types";

export const mockProperties: Property[] = [
  {
    id: "1",
    address: "1247 Maple Street",
    city: "Phoenix",
    state: "AZ",
    zip: "85001",
    propertyType: "Single Family",
    beds: 3,
    baths: 2,
    sqft: 1850,
    yearBuilt: 1998,
    estimatedValue: "$385,000",
    equity: "$142,000",
    equityLevel: "high",
    equityPercent: 37,
    ownerName: "Robert Martinez",
    ownerType: "Individual",
    lastSaleDate: "Mar 2019",
    lastSalePrice: "$243,000",
    openMortgage: "$243,000",
    tags: ["High Equity", "Long-term Owner"],
  },
  {
    id: "2",
    address: "534 Oak Avenue",
    city: "Phoenix",
    state: "AZ",
    zip: "85002",
    propertyType: "Single Family",
    beds: 4,
    baths: 2,
    sqft: 2100,
    yearBuilt: 2003,
    estimatedValue: "$420,000",
    equity: "$88,000",
    equityLevel: "medium",
    equityPercent: 21,
    ownerName: "Jennifer & Kyle Thompson",
    ownerType: "Individual",
    lastSaleDate: "Jan 2021",
    lastSalePrice: "$332,000",
    openMortgage: "$332,000",
    tags: ["Pre-Foreclosure"],
  },
  {
    id: "3",
    address: "891 Desert Rose Blvd",
    city: "Scottsdale",
    state: "AZ",
    zip: "85251",
    propertyType: "Single Family",
    beds: 5,
    baths: 3,
    sqft: 3200,
    yearBuilt: 2001,
    estimatedValue: "$720,000",
    equity: "$380,000",
    equityLevel: "high",
    equityPercent: 53,
    ownerName: "Desert Properties LLC",
    ownerType: "LLC",
    lastSaleDate: "Nov 2017",
    lastSalePrice: "$340,000",
    openMortgage: "$340,000",
    tags: ["High Equity", "LLC Owned", "Free & Clear"],
  },
  {
    id: "4",
    address: "2203 West Camelback Rd",
    city: "Phoenix",
    state: "AZ",
    zip: "85015",
    propertyType: "Multi-Family",
    beds: 6,
    baths: 4,
    sqft: 2800,
    yearBuilt: 1989,
    estimatedValue: "$545,000",
    equity: "$45,000",
    equityLevel: "low",
    equityPercent: 8,
    ownerName: "Harold & Susan Kim",
    ownerType: "Individual",
    lastSaleDate: "Aug 2022",
    lastSalePrice: "$500,000",
    openMortgage: "$500,000",
    tags: ["Absentee Owner"],
  },
];

export const mockLeads: Lead[] = [
  {
    id: "1",
    name: "Robert Martinez",
    address: "1247 Maple Street, Phoenix AZ",
    phone: "(602) 555-0142",
    email: "r.martinez@email.com",
    propertyValue: "$385,000",
    equity: "$142,000",
    motivation: "High",
    status: "Contacted",
    addedDate: "May 28, 2026",
    listName: "High Equity Phoenix",
  },
  {
    id: "2",
    name: "Jennifer Thompson",
    address: "534 Oak Avenue, Phoenix AZ",
    phone: "(602) 555-0287",
    email: "",
    propertyValue: "$420,000",
    equity: "$88,000",
    motivation: "High",
    status: "New",
    addedDate: "May 30, 2026",
    listName: "Pre-Foreclosure Q2",
  },
  {
    id: "3",
    name: "Desert Properties LLC",
    address: "891 Desert Rose Blvd, Scottsdale AZ",
    phone: "(480) 555-0399",
    email: "info@desertprop.com",
    propertyValue: "$720,000",
    equity: "$380,000",
    motivation: "Medium",
    status: "Negotiating",
    addedDate: "May 15, 2026",
    listName: "Scottsdale LLC",
  },
];

export const mockComps: Comp[] = [
  {
    id: "1",
    address: "1189 Maple Street",
    salePrice: "$372,000",
    saleDate: "Apr 2026",
    sqft: 1780,
    pricePerSqft: "$209",
    beds: 3,
    baths: 2,
    distance: "0.1 mi",
  },
  {
    id: "2",
    address: "1302 Elm Street",
    salePrice: "$391,500",
    saleDate: "Mar 2026",
    sqft: 1920,
    pricePerSqft: "$204",
    beds: 3,
    baths: 2,
    distance: "0.3 mi",
  },
  {
    id: "3",
    address: "1055 Oak Drive",
    salePrice: "$365,000",
    saleDate: "Feb 2026",
    sqft: 1750,
    pricePerSqft: "$209",
    beds: 3,
    baths: 2,
    distance: "0.4 mi",
  },
];
